name: CI DevOps

on:
  push:
    branches: [ "main", "master" ]

jobs:
  # Roteiro 5 / CD
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simular Build
        run: echo "Iniciando o build para o usuário Andre..."
   
  sast-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Executar Semgrep (Gerando JSON)
        run: semgrep scan --config auto --gitlab-sast -o gl-sast-report.json || true

      - name: Validar o relatório SAST (Script Python)
        run: |
          echo "Validando o relatório SAST..."
          python -c "
          import json
          with open('gl-sast-report.json') as f:
              report = json.load(f)
          vulnerabilities = report.get('vulnerabilities', [])
          if vulnerabilities:
              print(f'\n== Relatório de Vulnerabilidades ({len(vulnerabilities)} encontradas) ==')
              for vuln in vulnerabilities:
                  print('\n--- DETALHES DA FALHA ---')
                  print(json.dumps(vuln, indent=2))
              exit(1)
          else:
              print('Nenhuma vulnerabilidade encontrada.')
          "
          
  # Roteiro 4 / CI
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências (Flask e Coverage)
        run: pip install flask coverage

      - name: Rodar testes com Coverage
        run: python -m coverage run -m unittest -v tests/appTest.py

      - name: Exibir relatório de cobertura
        run: python -m coverage report

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Teste 2
        run: echo "Executando o test-job2 da Ação 1"
